[build]
  base = "server/client"
  publish = "server/client/build"
  functions = "server/server/netlify/functions"
  command = "npm install && npm run build"

[dev]
  framework = "#custom"

[functions]
  directory = "server/netlify/functions"
