[build]
  base = "server"
  command = "npm install && cd client && npm install && npm run build"
  publish = "client/build"
  functions = "netlify/functions"

[dev]
  framework = "#custom"

[functions]
  directory = "server/netlify/functions"
